export { default as Footer } from './Footer/Footer';
export { default as Features } from './Features/Features';
export { default as Team } from './Team/Team';
export { default as Header } from './Header/Header';
export { default as Intro } from './Intro/Intro';
export { default as Works } from './Works/Works';
export { default as BiographyItem } from './BiographyItem/BiographyItem';
export { default as FeaturesItem } from './FeaturesItem/FeaturesItem';
export { default as HomeItem } from './HomeItem/HomeItem';
